---
version: '3'
services:
  freqtrade_ours:
    #image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_ours
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_ours.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.ours.sqlite
      --config /freqtrade/user_data/config_ours.json
      --strategy ours

  freqtrade_hibou:
    image: freqtradeorg/freqtrade:develop_plot
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_hibou
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8081"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_hibou.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.hibou.sqlite
      --config /freqtrade/user_data/config_hibou.json
      --strategy hibou

  freqtrade_abeille:
    image: freqtradeorg/freqtrade:develop_plot
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_abeille
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8082"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_abeille.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.abeille.sqlite
      --config /freqtrade/user_data/config_abeille.json
      --strategy abeille

  freqtrade_rino:
    image: freqtradeorg/freqtrade:develop_plot
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_rino
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8083:8083"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_rino.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.rino.sqlite
      --config /freqtrade/user_data/config_rino.json
      --strategy rino

  freqtrade_lapin:
    image: freqtradeorg/freqtrade:develop_plot
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_lapin
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8084:8084"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_lapin.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.lapin.sqlite
      --config /freqtrade/user_data/config_lapin.json
      --strategy lapin