---
version: '3'
services:
  freqtrade_abeille:
    image: freqtradeorg/freqtrade:stable
<<<<<<< HEAD
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
=======
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
>>>>>>> upstream/develop
    restart: unless-stopped
    container_name: freqtrade_abeille
    volumes:
      - "./user_data:/freqtrade/user_data"
<<<<<<< HEAD
=======
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
>>>>>>> upstream/develop
    ports:
      - "0.0.0.0:8090:8090"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_abeille.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.abeille.sqlite
      --config /freqtrade/user_data/config_abeille.json
      --strategy abeille

  freqtrade_ours:
    #image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    #image: freqtradeorg/freqtrade:develop_freqai
    image: freqtradeorg/freqtrade:stable
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_ours
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "0.0.0.0:8091:8091"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_ours.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.ours.sqlite
      --config /freqtrade/user_data/config_ours.json
      --strategy ours


  freqtrade_hibou:
    image: freqtradeorg/freqtrade:stable
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_hibou
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "0.0.0.0:8092:8092"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_hibou.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.hibou.sqlite
      --config /freqtrade/user_data/config_hibou.json
      --strategy hibou

  freqtrade_koala:
    image: freqtradeorg/freqtrade:stable
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_koala
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "0.0.0.0:8094:8094"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_koala.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.koala.sqlite
      --config /freqtrade/user_data/config_koala.json
      --strategy koala